name: Terraform Pipeline

on:
  push:
    branches: [ main ]
    paths: [ 'terraform/**.tf', '.github/workflows/terraform.yml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'terraform/**.tf', '.github/workflows/terraform.yml' ]
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1

defaults:
  run:
    working-directory: terraform

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configura credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Instala Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan -out=plan.out

      - name: Upload plan.out
        uses: actions/upload-artifact@v4
        with:
          name: plan
          path: terraform/plan.out   # caminho relativo à raiz do repo

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: production  # approval acontece no Environment do GitHub
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configura credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Instala Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Baixa plan.out
        uses: actions/download-artifact@v4
        with:
          name: plan
          path: terraform  # baixa direto na pasta onde vamos rodar

      - name: terraform init
        run: terraform init

      - name: terraform apply
        run: terraform apply -auto-approve plan.out
