name: Terraform Pipeline

on:
  push:
    branches: [ main ]
    paths: [ 'terraform/**', '.github/workflows/terraform.yml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'terraform/**', '.github/workflows/terraform.yml' ]
  workflow_dispatch: {}

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform   # roda todos os comandos dentro de terraform/
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Init
        run: terraform init

      - name: Validate
        run: terraform validate

      - name: Plan
        run: terraform plan -out=plan.out   # gera plan.out dentro de terraform/

      - name: Upload plan.out
        uses: actions/upload-artifact@v4
        with:
          name: plan
          path: plan.out                    # caminho relativo a terraform/ (por causa do working-directory)
          if-no-files-found: error

  apply:
    name: Terraform Apply (manual / env protegido)
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: production
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AWS creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Download plan.out
        uses: actions/download-artifact@v4
        with:
          name: plan
          path: .                           # baixa em terraform/ por causa do working-directory

      - name: Init
        run: terraform init

      - name: Apply
        run: terraform apply -auto-approve plan.out
