name: Terraform Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configura credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instala Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Inicializa Terraform
        run: terraform init

      - name: Valida Terraform
        run: terraform validate

      - name: Gera plano
        run: terraform plan -out=plan.out

      - name: Upload do plano
        uses: actions/upload-artifact@v3
        with:
          name: plan
          path: plan.out

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: production
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configura credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instala Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Download do plano
        uses: actions/download-artifact@v3
        with:
          name: plan
          path: .

      - name: Inicializa Terraform
        run: terraform init

      - name: Aplica mudanças
        run: terraform apply -auto-approve plan.out
