name: Terraform Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch: {}

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform   # << roda dentro da pasta terraform
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configura credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instala Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=plan.out

      - name: Upload do plano
        uses: actions/upload-artifact@v4
        with:
          name: plan
          path: terraform/plan.out   # caminho relativo à raiz do repo

  apply:
    name: Terraform Apply (aprovado)
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: production   # exige aprovação na aba Environments
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configura credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instala Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Baixa o plano gerado
        uses: actions/download-artifact@v4
        with:
          name: plan
          path: .          # baixa em ./terraform por causa do working-directory

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve plan.out

