name: tf-dev-plan
on:
  pull_request:
    paths:
      - 'infra/terraform/environments/dev/**'
  push:
    branches: [ main ]
    paths:
      - 'infra/terraform/environments/dev/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform/environments/dev
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS (OIDC)
        if: ${{ secrets.AWS_OIDC_ROLE_ARN != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init (backend S3)
        run: terraform init -backend-config=backend.hcl

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan (dev)
        run: terraform plan -var-file="dev.tfvars" -no-color -input=false -lock=false

      - name: Comment plan on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            let out = execSync('terraform plan -var-file=dev.tfvars -no-color -input=false -lock=false', { cwd: 'infra/terraform/environments/dev' }).toString();
            const body = '### Terraform Plan (dev)\n```\n' + out.slice(0, 60000) + '\n```';
            github.rest.issues.createComment({ issue_number: context.issue.number, owner: context.repo.owner, repo: context.repo.repo, body });
