name: tf-hom-plan

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Debug repo tree
        run: |
          pwd
          ls -la
          command -v tree >/dev/null 2>&1 && tree -a -L 3 || find . -maxdepth 3 -type d -print

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: terraform plan -var-file=dev.tfvars -out=plan.out -input=false

      - name: Upload plan.out
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: terraform/plan.out
